In [17]:
import math
import numpy as np
#list with % of low emission Licensed Taxis operating in York per year from 2011 to 2019
yorkTaxis=[0.00,1.00,3.00,6.00,8.00,13.00,16.10,17.60,19.90]
#list with % of low emission Licensed Taxis operating in Leeds per year from 2011 to 2019
leedsTaxis=[0.50,1.20,2.30,5.00,7.80,14.30,17.10,17.30,20.90]
york = np.array(yorkTaxis)
leeds = np.array(leedsTaxis)

In [18]:
print(york.shape)
print(leeds.shape)

(9,)
(9,)


In [19]:
print(york.dtype)
print(leeds.dtype)

float64
float64


In [20]:
print(york[4:])
print(leeds[4:])

[ 8.  13.  16.1 17.6 19.9]
[ 7.8 14.3 17.1 17.3 20.9]


In [21]:
yorkMin = np.min(york)
yorkMax = np.max(york)
yorkMean = np.mean(york)
print(yorkMin, yorkMax, yorkMean)

leedsMin = np.min(leeds)
leedsMax = np.max(leeds)
leedsMean = np.mean(leeds)
print(leedsMin, leedsMax, leedsMean)


0.0 19.9 9.399999999999999
0.5 20.9 9.600000000000001


In [22]:
allData = np.concatenate((york, leeds))
sortedAllData = np.sort(allData)
print(sortedAllData)


[ 0.   0.5  1.   1.2  2.3  3.   5.   6.   7.8  8.  13.  14.3 16.1 17.1
 17.3 17.6 19.9 20.9]


In [23]:
allData2D = allData.reshape(9,2)
print(allData2D)

[[ 0.   1. ]
 [ 3.   6. ]
 [ 8.  13. ]
 [16.1 17.6]
 [19.9  0.5]
 [ 1.2  2.3]
 [ 5.   7.8]
 [14.3 17.1]
 [17.3 20.9]]


In [24]:
print(allData2D.T)

[[ 0.   3.   8.  16.1 19.9  1.2  5.  14.3 17.3]
 [ 1.   6.  13.  17.6  0.5  2.3  7.8 17.1 20.9]]


In [25]:
percentageDiff = []
for i in range(len(york)):
    percentageDiff.append(abs(york[i]-leeds[i]))
percentageDiff = np.array(percentageDiff)
print(percentageDiff)

[0.5 0.2 0.7 1.  0.2 1.3 1.  0.3 1. ]


In [26]:
def maxMinDiff(diffs):
    maxDiff = np.max(diffs)
    minDiff = np.min(diffs)
    meanDiff = np.mean(diffs)
    print(minDiff, maxDiff, meanDiff)
maxMinDiff(percentageDiff)

0.19999999999999996 1.3000000000000007 0.6888888888888891


In [27]:
def countEmissions():
    count = 0
    for i in range(len(york)):
        if york[i] < leeds[i]:
            count += 1
    print(count)
countEmissions()

5


In [38]:
yearStart = 2011
years = np.arange(2011, 2011+len(york))
years = years.astype(int)
np.set_printoptions(suppress=True)
print(years)
array2d = (years, york)
array2d = np.stack(array2d, 1)
print(array2d)

[2011 2012 2013 2014 2015 2016 2017 2018 2019]
[[2011.0    0.0]
 [2012.0    1.0]
 [2013.0    3.0]
 [2014.0    6.0]
 [2015.0    8.0]
 [2016.0   13.0]
 [2017.0   16.1]
 [2018.0   17.6]
 [2019.0   19.9]]
